/* field table */

enum if_1_list {
	_std_con_prd_no = 0,
	_std_prc_no,
	_std_prc_class_cd,
	_std_prc_nm,
	_std_prc_mea_cd,
	_std_tot_prc_tm,
	_std_tot_mc_tm,
	_std_piece_no,
	_std_stitch_no,
	_std_seam_no,
	_std_margin_width,
	_std_prc_level,
	_std_person_cnt,
	_std_remark,
	_std_voice_file_url,
	_std_movie_file_url,
};

enum if_2_list {
	_sew_con_prd_no = 0,
	_sew_prc_no,
	_sew_sub_prc_no,
	_sew_ptn_num,
	_sew_sub_ptn_num,
	_sew_machine_tp_cd,
	_sew_speed,
	_sew_stitch,
	_sew_nrb_press,
	_sew_trd_tns1,
	_sew_up_trd_tp1,
	_sew_up_trd_spec1,
	_sew_up_trd_clr1,
	_sew_dn_trd_tp1,
	_sew_dn_trd_spec1,
	_sew_dn_trd_clr1,
	_sew_ndl_tp1,
	_sew_ndl_spec1,
};

enum if_3_list {
	_cmd_con_prd_no,
	_cmd_con_prd_nm,
	_cmd_prc_no,
	_cmd_prc_nm,
	_cmd_tot_prd_amt,
	_cmd_tot_prd_day,
	_cmd_acc_prd_amt,
	_cmd_acc_prd_day,
	_cmd_work_dt,
	_cmd_mbr_id,
	_cmd_emp_nm,
	_cmd_b_prc_no,
	_cmd_b_prc_amt,
	_cmd_f_prc_no,
	_cmd_f_prc_amt,
	_cmd_today_alloc_amt,
	_cmd_today_add_amt,
	_cmd_today_tot_alloc_amt,
	_cmd_remark,
	_cmd_voice_path_url,
	_cmd_movie_path_url,
};

